services:
  em-app:
    build: .
    command: [ "./main", "--migrate=up" ]
    ports:
      - "8088:8088"
      - "8089:8089"
    depends_on:
      - em-redis
      - em-database
    restart: always
    networks:
      app_net:
        - app_net


  em-redis:
    image: redis:5
    container_name: em-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      app_net:

  em-database:
    image: docker.io/library/postgres:12
    container_name: em-database
    volumes:
      - em-db-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: sazito
      POSTGRES_PASSWORD: Sazito123
      POSTGRES_DB: sazito_evnet_manager
      POSTGRES_INITDB_ARGS: '--encoding=UTF8 --lc-collate=en_US.UTF-8 --lc-ctype=en_US.UTF-8'
    ports:
      - "9092:9092"


networks:
  app_net:

volumes:
  redis-data:
  md-db-data: